version: '3'

services:
  api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ".:/api"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: appmhor
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql